//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.InetOrders = new HashSet<InetOrder>();
            this.InetOrders1 = new HashSet<InetOrder>();
        }
    
        public int EmployeeID { get; set; }
        public int PositionID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<InetOrder> InetOrders { get; set; }
        public virtual ICollection<InetOrder> InetOrders1 { get; set; }
    }
}
