//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InetOrder
    {
        public InetOrder()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int InetOrderID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> TariffID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<bool> IsActual { get; set; }
        public Nullable<bool> AutomaticPayment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> AddressID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
