//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refill
    {
        public int RefillID { get; set; }
        public int AccountID { get; set; }
        public Nullable<System.DateTime> RefillTime { get; set; }
        public Nullable<decimal> Cash { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
