//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public Tariff()
        {
            this.InetOrders = new HashSet<InetOrder>();
        }
    
        public int TariffID { get; set; }
        public Nullable<int> TrafficLimit { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string TariffName { get; set; }
    
        public virtual ICollection<InetOrder> InetOrders { get; set; }
    }
}
